### ISSUE TITLE
Defintions for volume of supply.

### ISSUE THREAD

**Issue by chainhead** [token-taxonomy-initiative/TokenTaxonomyFramework#4]
Shouldn't there a term for the opposite of Singleton? Suppose, I want to create tokens for some interaction on a social network (e.g. like, etc.). The number is potentially infinite. OTOH, BTC has a finite supply. So, perhaps, under the category of Supply, there are three values, Singleton, Finite and Infinite (or at least, finitely large, etc.)

And, please change 'sub-dividable' to just divisible - the former is too contrived!

**Comment by marleyg** [comment]
Agree, these should be added in the next week or so.
