### ISSUE TITLE
small typo in readme

### ISSUE THREAD

**Issue by ibexboy** [token-taxonomy-initiative/TokenTaxonomyFramework#5]
Extra 'as' at end of paragraph

Non-fungible
A non-fungible token is unique. Hence a non-fungible token is not interchangeable with other tokens of the same type as they typically have different values. A property title is a good example of a non-fungible token where the title to a broken-down shack is not of the same value **as as** the title to a mansion.

**Comment by marleyg** [comment]
Thanks
