### ISSUE TITLE
Misspelling in the wireframe

### ISSUE THREAD

**Issue by vipinsun** [token-taxonomy-initiative/TokenTaxonomyFramework#7]
"Bill of Laden" should be "Bill of Lading"

![image](https://user-images.githubusercontent.com/4130345/69171610-4c6b6680-0aca-11ea-9344-ee54bea91e5c.png)

**Comment by vipinsun** [comment]
If I have access to the base editable diagram, I can create a corrected one and submit PR

**Comment by marleyg** [comment]
Fixed, thanks
